services:
  - type: web
    name: dailess-api
    runtime: node
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: UPLOAD_DIR
        value: uploads
